### ISSUE TITLE
Don't store internal data in msp.my

### ISSUE THREAD

**Issue by GnomTEC** [Ellypse/LibMSP#13]
msp.my is expected to be filled by the addon with data.

In my case i wipe msp.my before filling with new char data from internal addon db because empty fields are not stored there and i iterate through all stored fields and don't bother about which fields are not available and should be cleared.

Now i had to implement a workaround for 'TT' as it is used internal by LibMSP.

```
	local tt = msp.my['TT']
	wipe( msp.my )
	msp.my['TT'] = tt
	
	for field, value in pairs( GnomTEC_Badge.db.char["Flag"]["Fields"] ) do
		-- we also don't want to send ui escape sequences to others
		value = cleanpipe(value)
		msp.my[ field ] = value
	end
```

**Comment by Itarater** [comment]
msp.my.TT was always listed in the header information as being an internal field. (i.e., [in this old revision](https://github.com/Ellypse/LibMSP/blob/2414b6be367ccbacfd3ef37ce37f7aec4854ffea/LibMSP.lua#L14)).

I assumed this was actually the case, when working on the rewrite. It's there as a shortcut for elsewhere in the code to not have to add a special case there instead.
